import "./globals.css";
import { SocketProvider } from "./_utils/SocketProvider";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <React.StrictMode>
          <SocketProvider>{children}</SocketProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
